# Generated by Django 5.0.4 on 2024-04-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='priority',
            field=models.CharField(choices=[('High', 'Высокий'), ('Lower-high', 'Выше среднего'), ('Medium', 'Средний'), ('Lower-middle', 'Ниже среднего'), ('Low', 'Низкий')], default='High', max_length=50),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='status',
            field=models.CharField(choices=[('New', 'Новая'), ('In_progress', 'В работе'), ('Completed', 'Завершена')], default='New', max_length=50),
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='priority',
            field=models.CharField(choices=[('High', 'Высокий'), ('Lower-high', 'Выше среднего'), ('Medium', 'Средний'), ('Lower-middle', 'Ниже среднего'), ('Low', 'Низкий')], default='High', max_length=50),
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='status',
            field=models.CharField(choices=[('Review', 'Рассмотрение'), ('Accepted', 'Принято'), ('Rejected', 'Отклонено')], default='Review', max_length=50),
        ),
    ]
